export const envVariables = {
  EMAIL_PUBLIC: process.env.EMAIL_PUBLIC,
  EMAIL_SERVICE_ID: process.env.EMAIL_SERVICE_ID,
  EMAIL_TEMPLATE_ID: process.env.EMAIL_TEMPLATE_ID,
  PAYPAL_CLIENT_ID: process.env.PAYPAL_CLIENT_ID,
  PAYPAL_CLIENT_SECRET: process.env.PAYPAL_CLIENT_SECRET,
  DOGS_API: process.env.DOGS_API,
  NEXT_PUBLIC_VERCEL_URL: process.env.NEXT_PUBLIC_VERCEL_URL,
  NEXT_PUBLIC_SERVER_GRAPHQL: process.env.NEXT_PUBLIC_SERVER_GRAPHQL,
  DOGS_API_URI: process.env.DOGS_API_URI,
};
